Revert "Rework flake and overlay structures" due to downstream breakage
This reverts commit 152d075cc0cb9e19694d5fe3eafd2eee53129838, reversing
changes made to ffe47b90076067ad5dc25fe739d95a463bdf3c59.

Nix doesn't allow a dependent flake to have relative inputs.
```
error: cannot fetch input 'path:./systems.nix?lastModified=1&narHash=sh
a256-cyfZqnwhPNzdfQnmUUUVK5fon88TSm/0CwgE7Lf%2BLDU%3D' because it uses a relat
ive path
```

Closes #125